#!/bin/bash
# Training vs Voice Cloning Comparison

echo "🎤 Custom Voice - Training Options Comparison"
echo "=============================================="
echo ""
echo "📊 OPTION 1: FULL MODEL TRAINING"
echo "   Duration: 2-4 hours"
echo "   Quality: Very high (after convergence)"
echo "   Data requirement: Best with 500+ samples"
echo "   Resource usage: High GPU/CPU usage"
echo "   Resumable: Yes (from checkpoints)"
echo "   Command: python3 scripts/train_model.py"
echo ""
echo "📊 OPTION 2: VOICE CLONING (RECOMMENDED)"
echo "   Duration: 5-15 minutes"
echo "   Quality: High (immediate results)"
echo "   Data requirement: Works great with 80 samples"
echo "   Resource usage: Moderate"
echo "   Resumable: N/A (too fast to need)"
echo "   Command: python3 scripts/voice_clone.py"
echo ""
echo "🎯 RECOMMENDATION FOR YOUR DATASET:"
echo "   With 80 samples (~9 minutes), VOICE CLONING is better because:"
echo "   ✅ Faster results (minutes vs hours)"
echo "   ✅ Better quality with small datasets"
echo "   ✅ Uses state-of-the-art XTTS technology"
echo "   ✅ Perfect for your use case"
echo ""
echo "🚀 SUGGESTED WORKFLOW:"
echo "   1. Try voice cloning first (quick & high quality)"
echo "   2. If you want to experiment, try full training later"
echo "   3. Voice cloning will give you immediate usable results"
echo ""
echo "💡 COMMANDS TO RUN:"
echo "   cd /ssd/tts_project"
echo "   source coqui_env/bin/activate"
echo ""
echo "   # OPTION A: Quick voice cloning (RECOMMENDED)"
echo "   python3 scripts/voice_clone.py"
echo ""
echo "   # OPTION B: Full training (if you want to experiment)"
echo "   python3 scripts/train_model.py"
echo ""
echo "Choose your adventure! 🎯"